manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: mysterymath
      url-base: https://github.com/mysterymath

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: main
      import:
        name-allowlist:
          - cmsis
          - hal_nordic
    - name: microcosm-toolchain
      remote: mysterymath
      revision: main
      path: toolchain
